"use client";

import { AlertTriangle, Info } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { motion } from "framer-motion";

export default function Disclaimer() {
    return (
        <div className="max-w-4xl mx-auto py-12 space-y-12">
            <div className="space-y-4">
                <h1 className="text-4xl font-bold tracking-tight text-foreground">Medical Disclaimer</h1>
                <p className="text-xl text-muted-foreground">
                    Important information regarding the scope and limitations of this application.
                </p>
            </div>

            <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, delay: 0.2 }}
            >
                <Alert variant="destructive" className="border-l-4 shadow-lg bg-destructive/5 backdrop-blur-sm">
                    <motion.div
                        animate={{ rotate: [0, 10, -10, 0] }}
                        transition={{ repeat: Infinity, duration: 2, repeatDelay: 3 }}
                    >
                        <AlertTriangle className="h-5 w-5" />
                    </motion.div>
                    <AlertTitle className="text-xl font-bold ml-2">Not a Suggestion for Medical Treatment</AlertTitle>
                    <AlertDescription className="mt-4 ml-2 max-w-3xl leading-relaxed text-foreground/90">
                        <p className="mb-2">
                            The CardioCare application is a **demonstrative machine learning project** designed for educational and informational purposes only.
                        </p>
                        <p>
                            The predictions generated by this system are based on statistical patterns found in historical data. They **DO NOT** constitute a medical diagnosis, prognosis, or treatment plan. A "Low Risk" result does not guarantee health, and a "High Risk" result is not a definitive diagnosis of disease.
                        </p>
                    </AlertDescription>
                </Alert>
            </motion.div>

            <div className="grid gap-8 md:grid-cols-2">
                <div className="space-y-4">
                    <h3 className="text-xl font-semibold flex items-center gap-2 text-foreground">
                        <Info className="h-5 w-5 text-primary" />
                        Accuracy Limitations
                    </h3>
                    <p className="text-muted-foreground">
                        Machine Learning models are subject to errors (false positives and false negatives).
                        The model's accuracy (approx. 73%) means that roughly 1 in 4 predictions may be incorrect.
                        Always corroborate results with clinical advice.
                    </p>
                </div>
                <div className="space-y-4">
                    <h3 className="text-xl font-semibold flex items-center gap-2 text-foreground">
                        <AlertTriangle className="h-5 w-5 text-destructive" />
                        Emergency Situations
                    </h3>
                    <p className="text-muted-foreground">
                        Do not use this application in emergency situations. If you experience symptoms such as chest pain, shortness of breath, or dizziness, contact your family doctor or visit the nearest emergency room immediately.
                    </p>
                </div>
            </div>

            <div className="pt-8 border-t border-border">
                <p className="text-sm text-muted-foreground text-center">
                    By using this application, you acknowledge that you have read and understood this disclaimer.
                </p>
            </div>
        </div>
    );
}
